### ISSUE TITLE
xkcd-wrapper

### ISSUE THREAD

**Issue by Kronopt** [kyhau/have-a-smile#1]
Hi!

I just noticed on the repo page of [xkcd-wrapper](https://github.com/Kronopt/xkcd-wrapper) that you were using it on this project!
That's very cool 🥳

Unfortunately I also noticed you got version 0.2.1 in your [requirements](https://github.com/kyhau/have-a-smile/blob/master/smile/requirements.txt).
I released that 2 days ago, but it was bugged and I just now had the time to fix it...
[Version 0.2.2](https://github.com/Kronopt/xkcd-wrapper/releases/tag/v0.2.2) is out (and working!), so I'm just writing this to inform you of that.

I'm sorry if that caused any issues!

**Comment by Kronopt** [comment]
Also it should now be like this in the requirements file (in your case): `xkcd-wrapper[sync]==0.2.1`

**Comment by kyhau** [comment]
@Kronopt Thank you for letting me know the bug fix 👍
